name: "OpenType Sanitizer GitHub Action"
description: "A GitHub Action for opentype-sanitizer testing of font artifacts"
inputs:
  path: # id
    description: "Path to font binaries (wildcards are acceptable)"
    required: true
  update-pip: # id
    description: "Boolean for pip upgrade (default='false')"
    required: false
    default: "false" # options "true", "false"
  version: #id
    description: "opentype-sanitizer version (default='latest')"
    required: false
    default: "latest" # options: ["latest", "[VERSION NUMBER]"]

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "terminal"
  color: "blue"
